-- MIDA · Promociones y novedades
create table if not exists public.commercial_notices (
 id uuid primary key default gen_random_uuid(),
 title text not null, slug text not null unique, summary text, content text not null default '',
 image_url text, image_alt text, type text not null default 'promotion' check (type in ('promotion','notice','news','event')),
 status text not null default 'draft' check (status in ('draft','published','archived')),
 start_at date, end_at date, sort_order integer not null default 0, cta_label text default 'Solicitar información',
 seo_title text, seo_description text, created_by uuid references auth.users(id) on delete set null,
 published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.commercial_notices enable row level security;
drop policy if exists "Public can read published commercial notices" on public.commercial_notices;
create policy "Public can read published commercial notices" on public.commercial_notices for select using (status='published');
drop policy if exists "Active blog users manage commercial notices" on public.commercial_notices;
create policy "Active blog users manage commercial notices" on public.commercial_notices for all to authenticated using (exists(select 1 from public.blog_profiles p where p.user_id=auth.uid() and p.is_active=true)) with check (exists(select 1 from public.blog_profiles p where p.user_id=auth.uid() and p.is_active=true));
create index if not exists commercial_notices_status_dates_idx on public.commercial_notices(status,start_at,end_at,sort_order);

insert into public.commercial_notices(title,slug,summary,content,type,status,start_at,end_at,sort_order,seo_title,seo_description) values
('15% de descuento en Múltiples Suite Anual','15-descuento-multiples-suite-anual','Aprovecha 15% de descuento al adquirir o renovar dos o más sistemas Desktop dentro de una Compra Múltiple Suite.','<h2>Promoción Múltiples Suite Anual</h2><p>Durante octubre puedes obtener <strong>15% de descuento</strong> en renovaciones y licencias nuevas al comprar dos o más sistemas Desktop dentro de una Compra Múltiple Suite.</p><h3>Consideraciones</h3><p>No aplica para actualizaciones ni para XML en línea, Anticipa, Escritorio Virtual, sistemas mensuales, cambios de características, Kursa y CFDI Facturación en línea+, entre otras restricciones de la promoción.</p><p>Contacta a MIDA para validar qué combinación aplica para tu empresa.</p>','promotion','published','2026-10-01','2026-10-31',10,'15% en Múltiples Suite Anual CONTPAQi | MIDA','Obtén 15% de descuento en Múltiples Suite Anual CONTPAQi durante octubre. Consulta condiciones con MIDA.'),
('Cross Sell CONTPAQi: 15% en licencias nuevas','cross-sell-contpaqi-15-descuento','Si ya utilizas un sistema CONTPAQi, complementa tu operación con otro producto y obtén 15% de descuento.','<h2>Complementa los sistemas que ya utilizas</h2><p>La campaña Cross Sell ofrece <strong>15% de descuento en licencias nuevas</strong> hasta el 31 de octubre.</p><h3>Combinaciones principales</h3><ul><li>Contabilidad → Nóminas</li><li>Nóminas → Contabilidad</li><li>Comercial Premium → Contabilidad</li></ul><p>En MIDA podemos revisar tus sistemas actuales y ayudarte a identificar la combinación que mejor complemente tu operación.</p>','promotion','published','2026-10-01','2026-10-31',20,'Cross Sell CONTPAQi 15% de descuento | MIDA','15% de descuento en licencias nuevas CONTPAQi mediante combinaciones Cross Sell durante octubre.'),
('15% de descuento en actualizaciones CONTPAQi','15-descuento-actualizaciones-contpaqi','Actualiza tus sistemas CONTPAQi con 15% de descuento del 2 al 31 de octubre de 2026.','<h2>Mantén tus sistemas actualizados</h2><p>Del <strong>2 al 31 de octubre de 2026</strong> se ofrece 15% de descuento en actualizaciones de productos CONTPAQi bajo esquema tradicional.</p><p>Aplica para Contabilidad, Nóminas, Bancos, Comercial Premium, Comercial Start y Factura Electrónica, además de determinados incrementos de usuarios de acuerdo con las condiciones de cada licencia.</p><p>Podemos revisar la versión que utilizas actualmente y confirmar si tu licencia participa.</p>','promotion','published','2026-10-02','2026-10-31',30,'15% en actualizaciones CONTPAQi | MIDA','Actualiza Contabilidad, Nóminas, Bancos, Comercial Premium, Start o Factura Electrónica con 15% de descuento.'),
('Promoción CONTPAQi + Banorte','promocion-contpaqi-banorte','Clientes Banorte pueden acceder a descuentos especiales en licencias, renovaciones y migraciones a CONTPAQi.','<h2>Beneficios para clientes Banorte</h2><p>Los clientes Banorte pueden obtener <strong>30% de descuento</strong> en licencia nueva o renovación de CONTPAQi Bancos o Contabilidad.</p><p>Al migrar desde otro software y presentar la factura correspondiente, el descuento puede llegar hasta <strong>50%</strong>. También existen alternativas de hasta <strong>45%</strong> para otros productos como Nóminas, Comercial Premium, Factura Electrónica, Personia, Anticipa, Optimiza y Vende, sujetas a las condiciones de la campaña.</p><h3>Requisito</h3><p>Se solicita carátula de estado de cuenta o apertura de contrato Banorte.</p>','promotion','published','2026-10-01','2026-10-31',40,'Promoción CONTPAQi Banorte | MIDA','Descuentos especiales para clientes Banorte en licencias, renovaciones y migraciones de sistemas CONTPAQi.'),
('Actualiza tu versión para continuar timbrando CFDI','actualiza-contpaqi-para-continuar-timbrando','Revisa la versión de tus sistemas CONTPAQi para evitar afectaciones en la emisión de CFDI.','<h2>Revisa la versión que utilizas</h2><p>CONTPAQi está impulsando la actualización de versiones para mantener la emisión de CFDI.</p><p>Entre las versiones mínimas informadas se encuentran Comercial Premium 11.0.1 o superior, Comercial Start/Pro 11.0.1 o superior, Bancos 19 o superior, Factura Electrónica 13 o superior y Nóminas 18 o superior.</p><p>Si utilizas una versión anterior, contáctanos para revisar tu instalación y definir la actualización adecuada.</p>','notice','published','2026-10-01',null,50,'Versiones CONTPAQi para continuar timbrando | MIDA','Revisa si tu versión de CONTPAQi cumple con los requisitos para continuar emitiendo CFDI.'),
('Transición del Licenciamiento Tradicional a Anual','licenciamiento-tradicional-a-anual-contpaqi','CONTPAQi continúa la transición hacia el Licenciamiento Anual. Conoce los cambios previstos para los próximos años.','<h2>CONTPAQi avanza hacia el Licenciamiento Anual</h2><p>Durante diciembre de 2026 comenzarán nuevos cambios y durante 2027 las versiones mayores estarán cada vez más enfocadas al esquema anual.</p><p>Para 2028 las versiones tradicionales podrán seguir operando bajo determinadas condiciones, pero ya no podrán emitir ni descargar CFDI.</p><p>Si todavía trabajas con licenciamiento tradicional, en MIDA podemos revisar tu situación y ayudarte a planear la migración sin esperar al último momento.</p>','notice','published','2026-10-01',null,60,'Licenciamiento Anual CONTPAQi | MIDA','Conoce la transición de CONTPAQi del licenciamiento tradicional al anual y prepara tu empresa para los próximos cambios.'),
('CFDI en línea+ migra a CONTPAQi Vende','cfdi-en-linea-plus-migra-a-vende','CFDI en línea+ dejará de comercializarse y posteriormente de operar. Los clientes vigentes serán migrados a CONTPAQi Vende Inicial.','<h2>Cambio importante para usuarios de CFDI en línea+</h2><p>A partir del <strong>12 de octubre de 2026</strong> ya no se podrá adquirir CFDI en línea+ y el <strong>15 de enero de 2027</strong> dejará de operar.</p><p>Los clientes que todavía tengan vigencia serán migrados hacia <strong>CONTPAQi Vende Inicial</strong>. También se contempla una herramienta para apoyar el traslado de información.</p><p>Este cambio corresponde a CFDI en línea+. CFDI en línea tradicional continúa vigente.</p>','notice','published','2026-10-01','2027-01-15',70,'CFDI en línea+ migra a CONTPAQi Vende | MIDA','Conoce las fechas de descontinuación de CFDI en línea+ y la migración prevista hacia CONTPAQi Vende Inicial.'),
('Nuevo Escritorio Virtual a la Medida','escritorio-virtual-a-la-medida-contpaqi','Desde octubre las nuevas contrataciones de Escritorio Virtual permiten configurar recursos de acuerdo con las necesidades del cliente.','<h2>Una infraestructura más flexible</h2><p>Desde el <strong>5 de octubre</strong>, las nuevas contrataciones de Escritorio Virtual se realizan mediante Marketplace sobre SkyOne.</p><p>Ahora es posible configurar CPU, memoria RAM, almacenamiento y usuarios de acuerdo con las necesidades de cada empresa. Se mantienen modalidades de 320 y 720 horas mensuales y opciones de almacenamiento adicional desde 25 GB hasta 1 TB.</p><p>El material comercial señala un precio de $199 MXN mensuales por usuario adicional. Los clientes existentes sobre AWS pueden continuar renovando bajo su esquema actual.</p>','news','published','2026-10-05',null,80,'Escritorio Virtual a la Medida CONTPAQi | MIDA','Conoce el nuevo Escritorio Virtual a la Medida de CONTPAQi con recursos configurables para cada empresa.')
on conflict (slug) do update set title=excluded.title,summary=excluded.summary,content=excluded.content,type=excluded.type,status=excluded.status,start_at=excluded.start_at,end_at=excluded.end_at,sort_order=excluded.sort_order,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();


-- Ejecutar una sola vez en Supabase SQL Editor.
-- Relaciona promociones/avisos con las páginas de producto de MIDA.
alter table public.commercial_notices
  add column if not exists related_products text[] not null default '{}';

create index if not exists commercial_notices_related_products_gin
  on public.commercial_notices using gin (related_products);

comment on column public.commercial_notices.related_products is
  'Slugs de páginas de producto MIDA donde debe mostrarse la promoción o aviso.';
