export type SeoPage = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  intro: string;
  benefits: string[];
  features: string[];
  productPage?: boolean;
  image?: string;
  sourceUrl?: string;
  youtubeVideoId?: string;
  pricing?: { label: string; newPrice: string; renewalPrice: string; extraUser?: string }[];
};

export const seoPages: SeoPage[] = [
  { slug:"contpaqi-bancos", title:"CONTPAQi Bancos® | MIDA", h1:"CONTPAQi Bancos®", description:"Control de flujo de efectivo, conciliación y movimientos bancarios con CONTPAQi Bancos®.", eyebrow:"Control financiero", intro:"Controla ingresos, egresos, liquidez y movimientos bancarios con una solución integrada al ecosistema CONTPAQi®.", benefits:["Control de flujo de efectivo","Vinculación de CFDI y movimientos","Descarga de movimientos bancarios","Reportes para cobros y pagos"], features:["Saldos de CFDI","Conexión bancaria","Conciliación y control financiero","Integración con CONTPAQi®"], productPage:true, image:"/images/productos/bancos.png", sourceUrl:"https://www.contpaqi.com/bancos" },
  { slug:"contpaqi-xml-en-linea", title:"CONTPAQi XML en línea+® | MIDA", h1:"CONTPAQi XML en línea+®", description:"Descarga, organiza y valida CFDI emitidos y recibidos con CONTPAQi XML en línea+®.", eyebrow:"Gestión de CFDI", intro:"Recupera, organiza y valida CFDI de forma masiva y automatizada conectando tu operación con la información disponible ante el SAT.", benefits:["Descarga masiva de CFDI","Sincronización con el SAT","Validación de estatus","Gestión Multi-RFC"], features:["Descargas automatizadas","Validación de CFDI","Integración con ADD","Exportación y consulta"], productPage:true, image:"/images/productos/xml.png", sourceUrl:"https://www.contpaqi.com/xml-en-linea", pricing:[{label:"Anual · Multiempresa y Multiusuario",newPrice:"$1,790",renewalPrice:"$1,690"}] },
  { slug:"contpaqi-optimiza", title:"CONTPAQi Optimiza® | MIDA", h1:"CONTPAQi Optimiza®", description:"Gestión para despachos contables en la nube con CONTPAQi Optimiza®.", eyebrow:"Gestión contable en la nube", intro:"Centraliza clientes, obligaciones fiscales, tareas y documentos para mejorar la productividad y visibilidad de tu despacho contable.", benefits:["Gestión centralizada de clientes","Control de obligaciones fiscales","Alertas y tareas automatizadas","Coordinación del equipo"], features:["Gestión en la nube","Seguimiento ante la autoridad","Administración documental","Visibilidad operativa"], productPage:true, image:"/images/productos/optimiza.png", sourceUrl:"https://www.contpaqi.com/optimiza" },
  { slug:"contpaqi-anticipa", title:"CONTPAQi Anticipa® | MIDA", h1:"CONTPAQi Anticipa®", description:"Análisis fiscal y prevención de riesgos con CONTPAQi Anticipa®.", eyebrow:"Análisis fiscal", intro:"Analiza tu información fiscal para detectar inconsistencias, conciliar información y tomar decisiones oportunas.", benefits:["Detección de riesgos fiscales","Conciliación con el SAT","Análisis de IVA e ISR","Reportes a la medida"], features:["Información fiscal centralizada","Indicadores","Conciliación","Prevención y control"], productPage:true, image:"/images/productos/anticipa.png", sourceUrl:"https://www.contpaqi.com/anticipa" },
  { slug:"contpaqi-comercial-premium", title:"CONTPAQi Comercial Premium® | MIDA", h1:"CONTPAQi Comercial Premium®", description:"Administración comercial, inventarios y procesos de compra y venta con CONTPAQi Comercial Premium®.", eyebrow:"Administración comercial", intro:"Controla los procesos administrativos y comerciales de tu empresa con herramientas para inventarios, compras, ventas y toma de decisiones.", benefits:["Control de inventarios","Procesos de compra y venta","Información para decisiones","Operación multiusuario"], features:["Inventarios y costos","Compras y ventas","CFDI y procesos fiscales","Reportes y operación empresarial"], productPage:true, image:"/images/productos/comercial_premium.png", sourceUrl:"https://www.contpaqi.com/comercial-premium", pricing:[{label:"Anual Multi-RFC · 1 usuario",newPrice:"$10,490",renewalPrice:"$9,790",extraUser:"$2,590"}] },
  { slug:"contpaqi-cfdi-facturacion-en-linea", title:"CONTPAQi CFDI Facturación en Línea+® | MIDA", h1:"CONTPAQi CFDI Facturación en Línea+®", description:"Emisión de CFDI en línea, sin instalaciones, con CONTPAQi CFDI Facturación en Línea+®.", eyebrow:"Facturación en la nube", intro:"Emite CFDI desde internet con una solución en línea que se mantiene actualizada para facilitar el cumplimiento fiscal.", benefits:["100% en línea","Actualización fiscal","Emisión de CFDI 4.0","Movilidad"], features:["Emisión de comprobantes","Acceso desde navegador","Timbrado","Actualización conforme al SAT"], productPage:true, image:"/images/productos/cfdi_linea.png", sourceUrl:"https://www.contpaqi.com/cfdi-facturacion-en-linea" },
  { slug:"contpaqi-vende", title:"CONTPAQi Vende® | MIDA", h1:"CONTPAQi Vende®", description:"Ventas, compras, inventario, facturación y cobranza en la nube con CONTPAQi Vende®.", eyebrow:"Administración en la nube", intro:"Centraliza ventas, compras, inventario, facturación, cobranza y reportes para operar desde cualquier lugar.", benefits:["CFDI ilimitados según edición","Facturación en la nube","Control de ventas y compras","Cobranza e inventarios"], features:["Cotizaciones y pedidos","Compras y pagos","Cuentas por cobrar","Autofacturación"], productPage:true, image:"/images/productos/vende.png", sourceUrl:"https://www.contpaqi.com/vende" },
  { slug:"contpaqi-colabora", title:"CONTPAQi Colabora® | MIDA", h1:"CONTPAQi Colabora®", description:"Asistencia, comunicación y autoservicio de colaboradores con CONTPAQi Colabora®.", eyebrow:"Gestión de colaboradores", intro:"Centraliza asistencia, comunicación y procesos de recursos humanos mediante una plataforma web y app móvil.", benefits:["Consulta de CFDI","Registro de asistencia","Vacaciones y permisos","Gestión desde app móvil"], features:["Geolocalización","Control de incidencias","Autoservicio del colaborador","Integración con Nóminas"], productPage:true, image:"/images/productos/nominas.png", sourceUrl:"https://www.contpaqi.com/colabora" },
  { slug:"contpaqi-evalua", title:"CONTPAQi Evalúa® | MIDA", h1:"CONTPAQi Evalúa®", description:"Evaluación de riesgos psicosociales y apoyo al cumplimiento de NOM-035 con CONTPAQi Evalúa®.", eyebrow:"Bienestar laboral", intro:"Identifica, analiza y previene factores de riesgo psicosocial para apoyar la gestión de bienestar laboral y NOM-035.", benefits:["Evaluación de riesgos","Apoyo al cumplimiento NOM-035","Seguimiento de resultados","Gestión por número de empleados"], features:["Evaluaciones","Análisis","Planes por tamaño de empresa","Gestión en línea"], productPage:true, image:"/images/productos/evalua.png", sourceUrl:"https://www.contpaqi.com/evalua" },
  { slug:"contpaqi-kursa", title:"CONTPAQi Kursa® | MIDA", h1:"CONTPAQi Kursa®", description:"Plataforma de capacitación en línea sobre sistemas y temas fiscales con CONTPAQi Kursa®.", eyebrow:"Capacitación en línea", intro:"Crea, gestiona y aprovecha capacitación en línea con contenidos especializados disponibles para trabajar a tu ritmo.", benefits:["Autocapacitación en línea","Temas fiscales","Cursos de sistemas CONTPAQi®","Acceso flexible"], features:["E-learning","Cursos interactivos","Capacitación especializada","Disponibilidad en línea"], productPage:true, image:"/images/productos/generica.jpg", sourceUrl:"https://www.contpaqi.com/kursa" },
  { slug:"contpaqi-respaldos", title:"CONTPAQi Respaldos® | MIDA", h1:"CONTPAQi Respaldos®", description:"Almacenamiento y respaldo en la nube para información empresarial con CONTPAQi Respaldos®.", eyebrow:"Respaldo en la nube", intro:"Protege y administra información de tus sistemas CONTPAQi® con almacenamiento en la nube y acceso desde cualquier lugar.", benefits:["Información en la nube","Respaldos automáticos","Acceso controlado","Administración de archivos"], features:["Almacenamiento cifrado","Gestión de accesos","Carga y administración","Automatización de respaldos"], productPage:true, image:"/images/productos/respaldos1.png", sourceUrl:"https://www.contpaqi.com/respaldos" },
  { slug:"contpaqi-escritorio-virtual", title:"CONTPAQi Escritorio Virtual® | MIDA", h1:"CONTPAQi Escritorio Virtual®", description:"Acceso remoto a sistemas CONTPAQi® desde la nube con CONTPAQi Escritorio Virtual®.", eyebrow:"Infraestructura en la nube", intro:"Accede de forma remota a sistemas compatibles de CONTPAQi® desde un navegador y reduce la dependencia de infraestructura local.", benefits:["Acceso remoto seguro","Movilidad y flexibilidad","Respaldo y continuidad","Menor infraestructura local"], features:["Acceso por navegador","Recursos escalables","Respaldos","Compatibilidad con sistemas CONTPAQi®"], productPage:true, image:"/images/productos/escritorio.png", sourceUrl:"https://www.contpaqi.com/escritorio-virtual", youtubeVideoId:"RwbtfSRc56w" },
  { slug:"distribuidor-contpaqi-leon", title:"Distribuidor CONTPAQi® en León | MIDA", h1:"Distribuidor CONTPAQi® en León", description:"Venta, implementación, renovación y soporte de soluciones CONTPAQi® para empresas en León y el Bajío.", eyebrow:"Soluciones CONTPAQi®", intro:"Te ayudamos a elegir, implementar y mantener la solución CONTPAQi® adecuada para la operación de tu empresa.", benefits:["Asesoría para elegir la licencia adecuada","Implementación y configuración","Renovaciones y actualizaciones","Soporte especializado"], features:["Venta y renovación de licencias","Implementación y puesta en marcha","Actualizaciones y migraciones","Capacitación y soporte"] },
  { slug:"soporte-contpaqi-leon", title:"Soporte CONTPAQi® en León | MIDA", h1:"Soporte CONTPAQi® en León", description:"Soporte especializado para sistemas CONTPAQi®, SQL, timbrado, licenciamiento y operación empresarial en León.", eyebrow:"Soporte especializado", intro:"Atendemos incidencias de CONTPAQi® y su infraestructura relacionada para recuperar la continuidad de tu operación.", benefits:["Errores de timbrado","Problemas de licenciamiento","Fallas y optimización SQL","Atención remota especializada"], features:["Diagnóstico de incidencias","Revisión de servicios y bases de datos","Soporte de operación","Seguimiento técnico"] },
  { slug:"contpaqi-contabilidad", title:"CONTPAQi® Contabilidad en León | MIDA", h1:"CONTPAQi® Contabilidad en León", description:"Implementación y soporte de CONTPAQi® Contabilidad para empresas y despachos en León y el Bajío.", eyebrow:"Software contable", intro:"Implementamos CONTPAQi® Contabilidad y te acompañamos en su configuración, actualización y operación.", benefits:["Acompañamiento de implementación","Configuración según tu operación","Actualizaciones","Soporte especializado"], features:["Gestión de procesos contables","Configuración inicial","Puesta en marcha","Capacitación y soporte"], productPage:true, image:"/images/productos/contabilidad.png", sourceUrl:"https://www.contpaqi.com/contabilidad", pricing:[{label:"Anual Mono-RFC · 1 usuario",newPrice:"$4,590",renewalPrice:"$4,390",extraUser:"$1,690"},{label:"Anual Multi-RFC · 1 usuario",newPrice:"$6,190",renewalPrice:"$5,690",extraUser:"$1,690"}] },
  { slug:"contpaqi-nominas", title:"CONTPAQi® Nóminas en León | MIDA", h1:"CONTPAQi® Nóminas en León", description:"Implementación, capacitación y soporte de CONTPAQi® Nóminas en León y el Bajío.", eyebrow:"Gestión de nómina", intro:"Implementamos y damos soporte a CONTPAQi® Nóminas para mantener tus procesos de cálculo y timbrado operando correctamente.", benefits:["Implementación","Configuración","Capacitación","Soporte y actualizaciones"], features:["Configuración del entorno de nómina","Puesta en marcha","Acompañamiento en timbrado","Capacitación a usuarios"], productPage:true, image:"/images/productos/nominas.png", sourceUrl:"https://www.contpaqi.com/nominas", pricing:[{label:"Anual Mono-RFC · 1 usuario",newPrice:"$5,590",renewalPrice:"$5,290",extraUser:"$1,690"},{label:"Anual Multi-RFC · 1 usuario",newPrice:"$7,690",renewalPrice:"$7,390",extraUser:"$1,790"}] },
  { slug:"contpaqi-comercial-pro", title:"CONTPAQi® Comercial Pro | MIDA", h1:"CONTPAQi® Comercial Pro", description:"Implementación y soporte de CONTPAQi® Comercial Pro para inventarios, compras y ventas.", eyebrow:"Gestión comercial", intro:"Lleva el control de inventarios, compras y ventas con acompañamiento técnico para implementar CONTPAQi® Comercial Pro.", benefits:["Control de la operación comercial","Implementación acompañada","Configuración","Soporte especializado"], features:["Inventarios","Compras","Ventas","Configuración e implementación"], productPage:true, image:"/images/productos/comercial_pro.png", sourceUrl:"https://www.contpaqi.com/comercial-pro", pricing:[{label:"Anual Mono-RFC · 1 usuario",newPrice:"$10,090",renewalPrice:"$8,890",extraUser:"$2,490"},{label:"Anual Multi-RFC · 1 usuario",newPrice:"$11,290",renewalPrice:"$9,890",extraUser:"$2,690"}] },
  { slug:"contpaqi-factura-electronica", title:"CONTPAQi® Factura Electrónica | MIDA", h1:"CONTPAQi® Factura Electrónica", description:"Implementación y soporte de CONTPAQi® Factura Electrónica para emisión y administración de CFDI.", eyebrow:"Facturación electrónica", intro:"Te acompañamos en la implementación y operación de CONTPAQi® Factura Electrónica para administrar tus CFDI.", benefits:["Implementación","Configuración","Actualizaciones","Soporte"], features:["Emisión y administración de CFDI","Configuración inicial","Actualización del sistema","Acompañamiento técnico"], productPage:true, image:"/images/productos/factura_electronica.png", sourceUrl:"https://www.contpaqi.com/factura-electronica", pricing:[{label:"Anual Mono-RFC · 1 usuario",newPrice:"$2,690",renewalPrice:"$2,590",extraUser:"$990 licencia nueva / $890 renovación"},{label:"Anual Multi-RFC · 1 usuario",newPrice:"$3,990",renewalPrice:"$3,890",extraUser:"$1,290 licencia nueva / $1,190 renovación"}] },
  { slug:"contpaqi-personia", title:"CONTPAQi® Personia | MIDA", h1:"CONTPAQi® Personia", description:"Asesoría e implementación de CONTPAQi® Personia para gestión de capital humano.", eyebrow:"Capital humano", intro:"Conoce e implementa CONTPAQi® Personia con acompañamiento de MIDA para digitalizar procesos de capital humano.", benefits:["Asesoría","Implementación","Configuración","Acompañamiento"], features:["Evaluación de necesidades","Configuración","Implementación","Acompañamiento a usuarios"], productPage:true },
  { slug:"renovacion-contpaqi", title:"Renovación de licencias CONTPAQi® | MIDA", h1:"Renovación de licencias CONTPAQi®", description:"Renovación y actualización de licencias CONTPAQi® con asesoría especializada.", eyebrow:"Licenciamiento", intro:"Revisamos tu licenciamiento y te ayudamos a mantener tus sistemas CONTPAQi® actualizados.", benefits:["Revisión de licencias","Renovación","Actualizaciones","Asesoría"], features:["Revisión de vigencia","Identificación del sistema","Proceso de renovación","Acompañamiento posterior"] },
  { slug:"instalacion-contpaqi", title:"Instalación CONTPAQi® | MIDA", h1:"Instalación de sistemas CONTPAQi®", description:"Instalación y configuración de sistemas CONTPAQi® en equipos, redes y servidores.", eyebrow:"Implementación", intro:"Instalamos y configuramos sistemas CONTPAQi® considerando estaciones de trabajo, red, servidor y SQL.", benefits:["Instalación","Configuración","Entornos en red","Validación técnica"], features:["Revisión de requerimientos","Instalación del sistema","Configuración de red y SQL","Pruebas de funcionamiento"] },
  { slug:"migracion-contpaqi", title:"Migración CONTPAQi® | MIDA", h1:"Migración de sistemas CONTPAQi®", description:"Acompañamiento técnico para migraciones de sistemas CONTPAQi® e infraestructura relacionada.", eyebrow:"Migración", intro:"Planeamos y acompañamos la migración de tu entorno CONTPAQi® para reducir interrupciones en la operación.", benefits:["Planeación","Respaldos","Migración","Validación posterior"], features:["Evaluación del entorno","Respaldo previo","Migración controlada","Validación posterior"] },
  { slug:"servidores-contpaqi", title:"Servidores para CONTPAQi® | MIDA", h1:"Servidores para CONTPAQi®", description:"Servidores e infraestructura para ambientes CONTPAQi® empresariales.", eyebrow:"Infraestructura", intro:"Diseñamos y configuramos infraestructura de servidor para ambientes CONTPAQi® de acuerdo con las necesidades de tu empresa.", benefits:["Dimensionamiento","Configuración","SQL","Continuidad operativa"], features:["Evaluación de carga","Configuración de servidor","Entorno SQL","Mantenimiento y soporte"] },
  { slug:"optimizacion-sql", title:"Optimización SQL en León | MIDA", h1:"Optimización SQL en León", description:"Optimización y mantenimiento de bases de datos SQL para sistemas empresariales y CONTPAQi®.", eyebrow:"Bases de datos", intro:"Revisamos y optimizamos bases de datos SQL para mejorar estabilidad y desempeño de aplicaciones empresariales.", benefits:["Diagnóstico","Mantenimiento","Rendimiento","Buenas prácticas"], features:["Diagnóstico del entorno","Revisión de base de datos","Mantenimiento preventivo","Seguimiento"] },
  { slug:"polizas-soporte-ti", title:"Pólizas de soporte TI en León | MIDA", h1:"Pólizas de soporte TI en León", description:"Pólizas de soporte tecnológico para empresas en León con atención especializada.", eyebrow:"Soporte empresarial", intro:"Centraliza la atención tecnológica de tu empresa con una póliza de soporte orientada a continuidad operativa.", benefits:["Atención técnica","Mantenimiento","Seguimiento","Continuidad"], features:["Atención de incidencias","Seguimiento de solicitudes","Mantenimiento","Acompañamiento tecnológico"] },
  { slug:"cursos-contpaqi", title:"Cursos CONTPAQi® en León | MIDA", h1:"Cursos CONTPAQi® en León", description:"Capacitación y cursos de sistemas CONTPAQi® para empresas y usuarios en León.", eyebrow:"Capacitación", intro:"Capacitamos a usuarios y equipos de trabajo para aprovechar mejor las herramientas CONTPAQi®.", benefits:["Capacitación práctica","Temarios orientados al sistema","Atención a dudas","Enfoque empresarial"], features:["Capacitación por sistema","Sesiones prácticas","Resolución de dudas","Orientación a la operación"] },
];

export function getSeoPage(slug: string) {
  return seoPages.find((page) => page.slug === slug);
}
