export type SeoPage = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  eyebrow: string;
  intro: string;
  benefits: string[];
  features: string[];
  productPage?: boolean;
};

export const seoPages: SeoPage[] = [
  { slug:"distribuidor-contpaqi-leon", title:"Distribuidor CONTPAQi en León | MIDA", h1:"Distribuidor CONTPAQi en León", description:"Venta, implementación, renovación y soporte de soluciones CONTPAQi para empresas en León y el Bajío.", eyebrow:"Soluciones CONTPAQi", intro:"Te ayudamos a elegir, implementar y mantener la solución CONTPAQi adecuada para la operación de tu empresa.", benefits:["Asesoría para elegir la licencia adecuada","Implementación y configuración","Renovaciones y actualizaciones","Soporte especializado"], features:["Venta y renovación de licencias","Implementación y puesta en marcha","Actualizaciones y migraciones","Capacitación y soporte"] },
  { slug:"soporte-contpaqi-leon", title:"Soporte CONTPAQi en León | MIDA", h1:"Soporte CONTPAQi en León", description:"Soporte especializado para sistemas CONTPAQi, SQL, timbrado, licenciamiento y operación empresarial en León.", eyebrow:"Soporte especializado", intro:"Atendemos incidencias de CONTPAQi y su infraestructura relacionada para recuperar la continuidad de tu operación.", benefits:["Errores de timbrado","Problemas de licenciamiento","Fallas y optimización SQL","Atención remota especializada"], features:["Diagnóstico de incidencias","Revisión de servicios y bases de datos","Soporte de operación","Seguimiento técnico"] },
  { slug:"contpaqi-contabilidad", title:"CONTPAQi Contabilidad en León | MIDA", h1:"CONTPAQi Contabilidad en León", description:"Implementación y soporte de CONTPAQi Contabilidad para empresas y despachos en León y el Bajío.", eyebrow:"Software contable", intro:"Implementamos CONTPAQi Contabilidad y te acompañamos en su configuración, actualización y operación.", benefits:["Acompañamiento de implementación","Configuración según tu operación","Actualizaciones","Soporte especializado"], features:["Gestión de procesos contables","Configuración inicial","Puesta en marcha","Capacitación y soporte"], productPage:true },
  { slug:"contpaqi-nominas", title:"CONTPAQi Nóminas en León | MIDA", h1:"CONTPAQi Nóminas en León", description:"Implementación, capacitación y soporte de CONTPAQi Nóminas en León y el Bajío.", eyebrow:"Gestión de nómina", intro:"Implementamos y damos soporte a CONTPAQi Nóminas para mantener tus procesos de cálculo y timbrado operando correctamente.", benefits:["Implementación","Configuración","Capacitación","Soporte y actualizaciones"], features:["Configuración del entorno de nómina","Puesta en marcha","Acompañamiento en timbrado","Capacitación a usuarios"], productPage:true },
  { slug:"contpaqi-comercial-pro", title:"CONTPAQi Comercial Pro | MIDA", h1:"CONTPAQi Comercial Pro", description:"Implementación y soporte de CONTPAQi Comercial Pro para inventarios, compras y ventas.", eyebrow:"Gestión comercial", intro:"Lleva el control de inventarios, compras y ventas con acompañamiento técnico para implementar CONTPAQi Comercial Pro.", benefits:["Control de la operación comercial","Implementación acompañada","Configuración","Soporte especializado"], features:["Inventarios","Compras","Ventas","Configuración e implementación"], productPage:true },
  { slug:"contpaqi-factura-electronica", title:"CONTPAQi Factura Electrónica | MIDA", h1:"CONTPAQi Factura Electrónica", description:"Implementación y soporte de CONTPAQi Factura Electrónica para emisión y administración de CFDI.", eyebrow:"Facturación electrónica", intro:"Te acompañamos en la implementación y operación de CONTPAQi Factura Electrónica para administrar tus CFDI.", benefits:["Implementación","Configuración","Actualizaciones","Soporte"], features:["Emisión y administración de CFDI","Configuración inicial","Actualización del sistema","Acompañamiento técnico"], productPage:true },
  { slug:"contpaqi-personia", title:"CONTPAQi Personia | MIDA", h1:"CONTPAQi Personia", description:"Asesoría e implementación de CONTPAQi Personia para gestión de capital humano.", eyebrow:"Capital humano", intro:"Conoce e implementa CONTPAQi Personia con acompañamiento de MIDA para digitalizar procesos de capital humano.", benefits:["Asesoría","Implementación","Configuración","Acompañamiento"], features:["Evaluación de necesidades","Configuración","Implementación","Acompañamiento a usuarios"], productPage:true },
  { slug:"renovacion-contpaqi", title:"Renovación de licencias CONTPAQi | MIDA", h1:"Renovación de licencias CONTPAQi", description:"Renovación y actualización de licencias CONTPAQi con asesoría especializada.", eyebrow:"Licenciamiento", intro:"Revisamos tu licenciamiento y te ayudamos a mantener tus sistemas CONTPAQi actualizados.", benefits:["Revisión de licencias","Renovación","Actualizaciones","Asesoría"], features:["Revisión de vigencia","Identificación del sistema","Proceso de renovación","Acompañamiento posterior"] },
  { slug:"instalacion-contpaqi", title:"Instalación CONTPAQi | MIDA", h1:"Instalación de sistemas CONTPAQi", description:"Instalación y configuración de sistemas CONTPAQi en equipos, redes y servidores.", eyebrow:"Implementación", intro:"Instalamos y configuramos sistemas CONTPAQi considerando estaciones de trabajo, red, servidor y SQL.", benefits:["Instalación","Configuración","Entornos en red","Validación técnica"], features:["Revisión de requerimientos","Instalación del sistema","Configuración de red y SQL","Pruebas de funcionamiento"] },
  { slug:"migracion-contpaqi", title:"Migración CONTPAQi | MIDA", h1:"Migración de sistemas CONTPAQi", description:"Acompañamiento técnico para migraciones de sistemas CONTPAQi e infraestructura relacionada.", eyebrow:"Migración", intro:"Planeamos y acompañamos la migración de tu entorno CONTPAQi para reducir interrupciones en la operación.", benefits:["Planeación","Respaldos","Migración","Validación posterior"], features:["Evaluación del entorno","Respaldo previo","Migración controlada","Validación posterior"] },
  { slug:"servidores-contpaqi", title:"Servidores para CONTPAQi | MIDA", h1:"Servidores para CONTPAQi", description:"Servidores e infraestructura para ambientes CONTPAQi empresariales.", eyebrow:"Infraestructura", intro:"Diseñamos y configuramos infraestructura de servidor para ambientes CONTPAQi de acuerdo con las necesidades de tu empresa.", benefits:["Dimensionamiento","Configuración","SQL","Continuidad operativa"], features:["Evaluación de carga","Configuración de servidor","Entorno SQL","Mantenimiento y soporte"] },
  { slug:"optimizacion-sql", title:"Optimización SQL en León | MIDA", h1:"Optimización SQL en León", description:"Optimización y mantenimiento de bases de datos SQL para sistemas empresariales y CONTPAQi.", eyebrow:"Bases de datos", intro:"Revisamos y optimizamos bases de datos SQL para mejorar estabilidad y desempeño de aplicaciones empresariales.", benefits:["Diagnóstico","Mantenimiento","Rendimiento","Buenas prácticas"], features:["Diagnóstico del entorno","Revisión de base de datos","Mantenimiento preventivo","Seguimiento"] },
  { slug:"polizas-soporte-ti", title:"Pólizas de soporte TI en León | MIDA", h1:"Pólizas de soporte TI en León", description:"Pólizas de soporte tecnológico para empresas en León con atención especializada.", eyebrow:"Soporte empresarial", intro:"Centraliza la atención tecnológica de tu empresa con una póliza de soporte orientada a continuidad operativa.", benefits:["Atención técnica","Mantenimiento","Seguimiento","Continuidad"], features:["Atención de incidencias","Seguimiento de solicitudes","Mantenimiento","Acompañamiento tecnológico"] },
  { slug:"cursos-contpaqi", title:"Cursos CONTPAQi en León | MIDA", h1:"Cursos CONTPAQi en León", description:"Capacitación y cursos de sistemas CONTPAQi para empresas y usuarios en León.", eyebrow:"Capacitación", intro:"Capacitamos a usuarios y equipos de trabajo para aprovechar mejor las herramientas CONTPAQi.", benefits:["Capacitación práctica","Temarios orientados al sistema","Atención a dudas","Enfoque empresarial"], features:["Capacitación por sistema","Sesiones prácticas","Resolución de dudas","Orientación a la operación"] },
];

export function getSeoPage(slug: string) {
  return seoPages.find((page) => page.slug === slug);
}
