export const infoEmpresa = {
  nombre: "MIDA Tech Consulting",
  legal: "MIDA",
  dominio: "https://mida.mx",
  formspreeId: "xnjrojny",
  recaptchaSiteKey: "6LcnGwAtAAAAABFZ6OsWkCOoOWPH4kDD3rFbdw-R",
  portalSoporteUrl: "https://soporte-mida.vercel.app/login",
  telefonoTexto: "477 329 5727",
  telefonoEnlace: "4773295727",
  whatsappTexto: "477 188 8836",
  whatsappNumero: "5214771888836",
  whatsappMensajePredeterminado: "Hola MIDA, necesito asesoría o soporte técnico.",
  whatsappNumeroBot: "5214776336652",
  whatsappMensajePredeterminadoBot: "Hola, necesito atención de MIDA",
  direccionCompleta: "Blvr. Mariano Escobedo Pte. 4502 Int 401-A, San Isidro de Jerez, Centro de Negocios Plaza K2, 37530 León de los Aldama, Gto., México.",
  direccionLinea1: "Blvr. Mariano Escobedo Pte. 4502 Int 401-A, San Isidro de Jerez, Centro de Negocios Plaza K2",
  direccionLinea2: "León, Guanajuato, México.",
  correoContacto: "dulce@mida.mx",
  googleAnalyticsId: "G-XXXXXXX",
};
